version: '3'

services:

  php-test:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html:rw
      - ./30-custom.ini:/usr/local/etc/php/conf.d/30-custom.ini      
    extra_hosts:
      - host.docker.internal:host-gateway
      
#     networks:
#        isolated-nw:
#           aliases:
#             - php
# networks:
#   isolated-nw:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 172.242.0.0/24
